[project]
name = "kimi-docs-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.62.0",
    "langchain-core>=1.2.11",
    "pypdf>=6.6.2",
    "python-dotenv>=1.2.1",
]
